# Generated by Django 5.1 on 2024-08-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agence', models.CharField(max_length=200)),
                ('nb_ventes', models.IntegerField(default=1)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
